version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=<postgres User>
      - POSTGRES_PASSWORD=<postgres PW>
  backend:
    build: backend/MyProject/.
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver  0.0.0.0:8000 "
    container_name: backend
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    container_name: frontend
    build:
      context: frontend/.
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'
    depends_on:
      - backend
