# Generated by Django 3.1.4 on 2020-12-23 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20201216_1136'),
        ('collection', '0002_collection_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='group.group'),
        ),
    ]
