# Generated by Django 3.1.4 on 2020-12-16 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=100, null=True)),
                ('place', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('state_code', models.CharField(max_length=100, null=True)),
                ('province', models.CharField(max_length=100, null=True)),
                ('province_code', models.CharField(max_length=100, null=True)),
                ('community', models.CharField(max_length=100, null=True)),
                ('community_code', models.CharField(max_length=100, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('longitude', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dialect',
            fields=[
                ('dialect', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DialectWord',
            fields=[
                ('word', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lexeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('kind', models.CharField(choices=[('N', 'noun'), ('V', 'verb'), ('Aj', 'adjective'), ('Av', 'adverb'), ('P', 'phrase')], max_length=255)),
                ('dialectWord', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dialect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialectWords', to='lexeme.dialect')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialectWords', to='lexeme.address')),
            ],
        ),
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronunciation', models.CharField(max_length=100)),
                ('dialectWord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciations', to='lexeme.lexeme')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(max_length=100)),
                ('dialectWord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='lexeme.lexeme')),
            ],
        ),
        migrations.CreateModel(
            name='Etymology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etymology', models.CharField(max_length=100)),
                ('dialectWord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etymologies', to='lexeme.lexeme')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lexemes', models.ManyToManyField(related_name='categories', to='lexeme.Lexeme')),
            ],
        ),
    ]
