# Generated by Django 3.1.4 on 2021-03-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexeme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lexemecontent',
            old_name='Lexeme',
            new_name='lexeme',
        ),
    ]
