# Generated by Django 3.1.4 on 2021-03-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexeme', '0002_auto_20210304_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexemecontent',
            name='lexeme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='lexeme.lexeme'),
        ),
    ]
