# Generated by Django 3.1.4 on 2021-03-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexeme', '0003_auto_20210304_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lexemecontent',
            name='author',
        ),
    ]
