# Generated by Django 3.1.4 on 2021-03-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexeme', '0004_auto_20210329_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexemecontent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
