# Generated by Django 3.1.4 on 2021-03-04 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexeme', '0004_remove_lexemecontent_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexeme',
            name='content',
            field=models.OneToOneField(null=True,on_delete=django.db.models.deletion.CASCADE, related_name='activeLexeme', to='lexeme.lexemecontent'),
            preserve_default=False,
        ),
    ]
