# Generated by Django 3.1.4 on 2021-04-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexeme', '0006_lexeme_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etymology',
            name='etymology',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='example',
            name='example',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lexemecontent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lexemecontent',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='message',
            field=models.TextField(),
        ),
    ]
