# Generated by Django 3.1.4 on 2021-03-04 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_create_collection', models.BooleanField(default=True)),
                ('public_create_collection', models.BooleanField(default=False)),
                ('need_password', models.BooleanField(default=False)),
                ('join_password', models.CharField(blank=True, max_length=100, null=True)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('members', models.ManyToManyField(related_name='groups', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupsOwned', to=settings.AUTH_USER_MODEL)),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='group.groupsettings')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
