# Generated by Django 3.1.4 on 2020-12-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='memebers',
            new_name='members',
        ),
    ]
