# Generated by Django 3.1.4 on 2021-03-04 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('lexeme', '0001_initial'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorite',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.collection'),
        ),
        migrations.AddField(
            model_name='account',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_home', to='lexeme.address'),
        ),
        migrations.AddField(
            model_name='account',
            name='locations',
            field=models.ManyToManyField(to='lexeme.Address'),
        ),
    ]
