# Generated by Django 3.1.3 on 2020-12-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='user', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
